### ISSUE TITLE
Interpolate mode for donwstream tasks

### ISSUE THREAD

**Issue by czczup** [facebookresearch/mae#10]
Hello, thank you for creating this awesome algorithm! 
I have a problem with applying MAE pre-trained weights in downstream tasks. Is the interpolation mode of position encoding bicubic?
If I train mask-rcnn, will the performance go up by simply replacing the deit weight with mae weight?

**Comment by KaimingHe** [comment]
You may use bicubic interpolation. As MAE uses sin-cos embedding, you may also use sin-cos of another size. They should be similar.
