### ISSUE TITLE
ImageNet-C numbers

### ISSUE THREAD

**Issue by shoaibahmed** [facebookresearch/mae#104]
Hi.

Thank you for sharing a very clean and extensible repository. I am confused regarding the metric that you are reporting for ImageNet-C. Is it just the average of the per-corruption average error rate? Or is it the relative mCE (relative w.r.t. AlexNet as reported in the original paper)?

I have tried the average of the per-corruption average error rate and it is vastly different (mean error rate of 27.91% for ViT-H and 37.98% for ViT-B). Although these results are better in terms of robustness, I am assuming that you reported something else which I would like to reproduce. So just want to clarify that.

Thank you once again for putting in a lot of effort for this!

**Comment by Jeff-LiangF** [comment]
Same here, I use [robustness](https://github.com/hendrycks/robustness) repo and I get for ViT-B:

`mCE (unnormalized by AlexNet errors) (%): 37.77`

**Comment by endernewton** [comment]
Please use the AlexNet normalized values, the results in the paper are also verified by another group using the repo.
