### ISSUE TITLE
Implementation of submitit_pretrain.py

### ISSUE THREAD

**Issue by wany1d1001** [facebookresearch/mae#106]
Hi,
I got a basic question:
When I use submiteit_pretrain.py it only creates a job folder and nothing happens after. I passed in the arguments like this:
`python submitit_pretrain.py     --nodes 2     --use_volta32     --batch_size 64     --model mae_vit_base_patch16     --norm_pix_loss     --mask_ratio 0.75     --epochs 100     --warmup_epochs 2     --blr 1.5e-4 --weight_decay 0.05     --data_path /user/test_data`

Could you explain how to make it start training with this file please? Many thanks

**Comment by Aurora-slz** [comment]
Hi, I met the same question. Have you slove it?

**Comment by wany1d1001** [comment]
> 
Because cuda out of memory in my case. I decreased batch size and run main_pretrain.py solved the issue

**Comment by wany1d1001** [comment]
> 

Because cuda out of memory in my case. I decreased batch size and run main_pretrain.py solved the issue
