### ISSUE TITLE
Doubts about the Position Encoding

### ISSUE THREAD

**Issue by chinmay5** [facebookresearch/mae#11]
Thank you so much for releasing the code.

I had a small doubt about the position encoding generated for the 2d sequence. In the file [pos_embed.py](https://github.com/facebookresearch/mae/blob/6a2ba402291005b003a70e99f7c87d1a2c376b0d/util/pos_embed.py#L42) we have divided the input sequence into two groups of size `D/2` and I am not sure the reason for it. If we have to move to higher dimensions, say 3, how should the same be done? Should we divide the sequence into three blocks (and make sure that individual blocks are of even size)?

**Comment by KaimingHe** [comment]
You may simply set the third dim as `D - D // 3 - D // 3`
