### ISSUE TITLE
distributed training has the same speed as single gpu training

### ISSUE THREAD

**Issue by ShihaoShao-GH** [facebookresearch/mae#113]
First, thanks for the great work.
Unfortunately, here I faced something really weird. I tried to train MAE on my single node with, 

`python -m torch.distributed.launch --nproc_per_node=4 main_pretrain.py     --batch_size 16     --model mae_vit_base_patch16     --norm_pix_loss     --mask_ratio 0.75     --epochs 800     --warmup_epochs 0     --blr 1.5e-4 --weight_decay 0.05     --data_path /home/shaoshihao`

Something goes weirdly is, it just run at the same speed as i ran that on single gpu with the command,
`python main_pretrain.py     --batch_size 64     --model mae_vit_base_patch16     --norm_pix_loss     --mask_ratio 0.75     --epochs 800     --warmup_epochs 0     --blr 1.5e-4 --weight_decay 0.05     --data_path /home/shaoshihao`

I tracked the GPU status and it looks good. The 4 GPUs are all ~100% utilization rate when i used 4 gpus.

Any advice will be deeply appreciated.

**Comment by ZiboZ** [comment]
are you using distributedSampler or normal randomSampler

**Comment by ShihaoShao-GH** [comment]
> are you using distributedSampler or normal randomSampler

DistributedSampler

**Comment by daisukelab** [comment]
@LouieShao Hi, it seems to depend on several factors, such as the storage speed I have experienced with several machines spanning from a PC with 2 A6000s to a server with 4 A100s. This is an example of my command line for 4 A100s, pre-train fast enough. This will pre-train with a batch size of 2048, then you might add an extra option `--accum_iter 4` to follow the exact setting of the paper.

```sh
OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=4 main_pretrain.py \
--output_dir pt300_mae --log_dir pt300_mae \
--batch_size 512 \
--model mae_vit_base_patch16 \
--norm_pix_loss \
--mask_ratio 0.75 \
--warmup_epochs 10 --epochs 300 \
--blr 1.5e-4 --weight_decay 0.05 \
--data_path /data/datasets/ILSVRC2012
```

**Comment by ShihaoShao-GH** [comment]
> @LouieShao Hi, it seems to depend on several factors, such as the storage speed I have experienced with several machines spanning from a PC with 2 A6000s to a server with 4 A100s. This is an example of my command line for 4 A100s, pre-train fast enough. This will pre-train with a batch size of 2048, then you might add an extra option `--accum_iter 4` to follow the exact setting of the paper.
> 
> ```shell
> OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=4 main_pretrain.py \
> --output_dir pt300_mae --log_dir pt300_mae \
> --batch_size 512 \
> --model mae_vit_base_patch16 \
> --norm_pix_loss \
> --mask_ratio 0.75 \
> --warmup_epochs 10 --epochs 300 \
> --blr 1.5e-4 --weight_decay 0.05 \
> --data_path /data/datasets/ILSVRC2012
> ```

I tried the same command on my 4 A100s and it really works! It only takes 8 min. per epoch. Maybe training only with large batch size may benefit from DDP. Thanks so much for your help.

**Comment by ZiboZ** [comment]
> 
Hi, in this setting your actual batch size is 16 times 512 instead of 4 * 512 (accum is set to 4). Thus the "speed up" may also partially contributed to the --accum parameter.

**Comment by jafarinia** [comment]
anyone knows why for single gpu both python and torchrun work? do they work exactly the same in single gpu setting?
