### ISSUE TITLE
How to use only VIT Encoder with pretrained weight, any example?

### ISSUE THREAD

**Issue by lonngxiang** [facebookresearch/mae#13]

**Comment by KaimingHe** [comment]
The fine-tuning process is essentially a usage of the pre-trained ViT encoder. See the instruction on how to do fine-tuning: https://github.com/facebookresearch/mae/blob/main/FINETUNE.md

**Comment by rchennnn** [comment]
If you wish to extract only the encoder, see [lines 233 to 259](https://github.com/facebookresearch/mae/blob/efb2a8062c206524e35e47d04501ed4f544c0ae8/main_finetune.py#L233C4-L259C21)

Then set model.head to be the identity.
