### ISSUE TITLE
pretrain error for import timm

### ISSUE THREAD

**Issue by chos1npc** [facebookresearch/mae#149]
I want to reproduce the experiment, but I got some mistake for import timm, I follow pretrain.md to implement this code, but it's told me "ImportError: cannot import name 'container_abcs' from 'torch._six' (/home/mmlab206/anaconda3/envs/aicup/lib/python3.10/site-packages/torch/_six.py)",  I already downloaded timm==0.3.2, I have no idea to solve that problem thanks.

**Comment by xcharxlie** [comment]
@chos1npc Hi there, I met the same issue, did you solve it?

**Comment by RohitKeshari** [comment]
try this https://github.com/facebookresearch/mae/issues/58#issuecomment-1329221448
