### ISSUE TITLE
Use VIT encoder with pretrained weight to do Image Recalls, it didn't work out very well

### ISSUE THREAD

**Issue by lonngxiang** [facebookresearch/mae#15]

**Comment by lonngxiang** [comment]
Images related to the first image recall

![image](https://user-images.githubusercontent.com/40717349/149446922-a717d9b7-549d-4098-b02d-43070ecdae2f.png)

**Comment by lonngxiang** [comment]
I'm through removing some code on timm library visdon_transformer. py file  to get 768-dimensional image vector

![image](https://user-images.githubusercontent.com/40717349/149449165-196bfe6a-7217-416d-ba02-fac47057b5e1.png)

**Comment by KaimingHe** [comment]
I suggest to do fine-tuning appropriately based on your task.
