### ISSUE TITLE
Release of MAE decoder

### ISSUE THREAD

**Issue by ustcwhy** [facebookresearch/mae#155]
Thanks for your great work !
MAE is very effective on many downstream tasks, but I noticed that you only seem to release the encoder part. Do you plan to release the complete model checkpoint in the future, including the decoder part ?

**Comment by alekhka** [comment]
I think you can find them on the [Colab notebook ](https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb)

It has links to these two weights - 
```
https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_large.pth
https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_large_ganloss.pth
```

I wanted the base model so I replaced "large" with "base" and luckily they have uploaded it too!
```
https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_base.pth
```

**Comment by ustcwhy** [comment]
> I think you can find them on the [Colab notebook ](https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb)
> 
> It has links to these two weights -
> 
> ```
> https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_large.pth
> https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_large_ganloss.pth
> ```
> 
> I wanted the base model so I replaced "large" with "base" and luckily they have uploaded it too!
> 
> ```
> https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_base.pth
> ```

Thanks ! I also found the MAE with its decoder in Huggingfacec~
