### ISSUE TITLE
Does this implement support timm > 0.3.2? 

### ISSUE THREAD

**Issue by verazuo** [facebookresearch/mae#17]
Hi,

Thanks for releasing this awesome work! 

I notice the code will check the version of timm. 
```
assert timm.__version__ == "0.3.2" # version check
```

Does this implement support updated timm, e.g. 0.4.12? 

Thanks!

Best,
Vera

**Comment by KaimingHe** [comment]
Our code was written and verified in `timm==0.3.2`. We have not verified other versions. Our collected feedbacks from other users suggest that 0.4.12 works well too. It could be used with caution.

**Comment by scaomath** [comment]
0.4.12 does not work, the author had since deleted the redundant `qk_scale` in the attention block.
See rwightman/pytorch-image-models#1091

I modified the corresponding part a little bit and inference does work in the newest `timm` which is 0.5.4.

**Comment by verazuo** [comment]
> 0.4.12 does not work, the author had since deleted the redundant `qk_scale` in the attention block. See [rwightman/pytorch-image-models#1091](https://github.com/rwightman/pytorch-image-models/pull/1091)
> 
> I modified the corresponding part a little bit and inference does work in the newest `timm` which is 0.5.4.

Yes, I thought we only need to remove `qk_scale` to make `timm==0.4.12` work. The version of timm won't effect the performance of MAE model.

**Comment by scaomath** [comment]
> > 0.4.12 does not work, the author had since deleted the redundant `qk_scale` in the attention block. See [rwightman/pytorch-image-models#1091](https://github.com/rwightman/pytorch-image-models/pull/1091)
> > I modified the corresponding part a little bit and inference does work in the newest `timm` which is 0.5.4.
> 
> Yes, I thought we only need to remove `qk_scale` to make `timm==0.4.12` work. The version of timm won't effect the performance of MAE model.

Shall I submit a PR?

**Comment by rwightman** [comment]
Hello all, `qk_scale=None` should be removed from the args, that arg was a workaround for a difference between my initial vit impl and the official impl that came out afterwards, I've since removed the arg as it doesn't have any valid use case I can think of, the default is already None (when it existed) so removing the arg here would work with all versions of `timm` vit

**Comment by endernewton** [comment]
Yes this is the only difference to make for the code to work with 0.4.12. We have confirmed on our side as well. Cc @ronghanghu
