### ISSUE TITLE
Question about positional embedding?

### ISSUE THREAD

**Issue by Sekunde** [facebookresearch/mae#18]
Hi, thanks for the great work!

I have a small question regarding the positional embedding:
In this line https://github.com/facebookresearch/mae/blob/6a2ba402291005b003a70e99f7c87d1a2c376b0d/util/pos_embed.py#L28
it seems to return [grid_w, grid_h]

However, in line 
https://github.com/facebookresearch/mae/blob/6a2ba402291005b003a70e99f7c87d1a2c376b0d/util/pos_embed.py#L42
it seems that grid_w is used for making emd_h? or did I miss something?

**Comment by KaimingHe** [comment]
Good catch. It looks like the naming of `emb_h` and `emb_w` in `get_2d_sincos_pos_embed_from_grid` are not ideal (need o verify):
https://github.com/facebookresearch/mae/blob/6a2ba402291005b003a70e99f7c87d1a2c376b0d/util/pos_embed.py#L38-L46

It should be named as:
```
    emb_w = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[0])  # (H*W, D/2)
    emb_h = get_1d_sincos_pos_embed_from_grid(embed_dim // 2, grid[1])  # (H*W, D/2)

    emb = np.concatenate([emb_w, emb_h], axis=1) # (H*W, D)
```
This produces exactly the same `emb` as the original code.

Note that if you only swap `grid[0]` and `grid[1]`, it does not produce the same `emb`. If so, it should still work if you do pre-training using the modified code, but it would break our pre-trained checkpoints as `emb` was changed.
