### ISSUE TITLE
Could you provide the pretrained checkpoints of both encoder and decoder in MAE?

### ISSUE THREAD

**Issue by tangky22** [facebookresearch/mae#188]
Only the pretrained checkpoints of the encoder of MAE are provided in the README file. Could you also provide the pretrained checkpoints of the decoder so that I can pretrain the whole MAE on different datasets? Thanks!

**Comment by hhhhzp** [comment]
already solved in #8

**Comment by tangky22** [comment]
> already solved in #8

ok, thanks a lot
