### ISSUE TITLE
Different masking strategies

### ISSUE THREAD

**Issue by chinmay5** [facebookresearch/mae#20]
Thank you so much for releasing the code. 

In the paper, there are experiments with different masking strategies such as `random`. `block` and `grid`. The code implementation includes only the `random` strategy. Is there any plan to also release the code for other strategies?

**Comment by KaimingHe** [comment]
This can be easily implemented by modifying the code here:

https://github.com/facebookresearch/mae/blob/main/models_mae.py#L132-L136
