### ISSUE TITLE
How to pretrain mae in 1 node with 8 gpus?

### ISSUE THREAD

**Issue by yanjk3** [facebookresearch/mae#25]
I m trying to pretrain a vit_small model in 1 node with 8 gpus, but the submitit_pretrain.py goes wrong with:
Traceback (most recent call last):
  File "submitit_pretrain.py", line 131, in <module>
    main()
  File "submitit_pretrain.py", line 89, in main
    args.job_dir = get_shared_folder() / "%j"
  File "submitit_pretrain.py", line 39, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available

it seems like that I have no shared folder, so how can I pretrain mae in 1 node with 8 gpus?
Thanks for your exciting job!!

**Comment by yanjk3** [comment]
well, I find that I can use main_pretrain.py to train the model...

**Comment by Liu-SD** [comment]
I find that only 1 gpu is utilized when I run "python main_pretrain.py". 
What's the option for 1 node N gpus training? @yanjk3 Thanks~

**Comment by RechelTeamo** [comment]
i use CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 main_pretrain.py --data_path /dockerdata/imagenet/imagenet --batch_size 64 as my sh file but only one Cuda is used. So can you tell me how can I use 8gpus.. thank you

**Comment by Liu-SD** [comment]
@RechelTeamo Maybe you can try
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 -m torch.distributed.launch --nproc_per_node=8 main_pretrain.py --data_path /dockerdata/imagenet/imagenet --batch_size 64

**Comment by JunMa11** [comment]
Dear all @yanjk3 @Liu-SD @RechelTeamo @likethesky ,

How long does it take to finish the training on 8 GPUs?

**Comment by RechelTeamo** [comment]
> 

OK, thank u very much. I use this code and it worked. But sometimes I meet the problem 
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
After this information, the program will be killed. 
Do u meet the same problem? thanks a lot.

**Comment by samanthawyf** [comment]
"After this information, the program will be killed."
Have you solved the problem and how? Thanks.

**Comment by RachelTeamo** [comment]
> etting OMP_NUM_THREADS environm

yes. I Solved it. You must check your code carefully because there is something wrong.

**Comment by kaushikb258** [comment]
This did not work for me. Code gets stuck inside init_distributed_mode() at the barrier() call. Any suggestions?
