### ISSUE TITLE
Could you please give the code to train ViT from scratch?

### ISSUE THREAD

**Issue by Freder-chen** [facebookresearch/mae#28]
I would like to know the higher baseline stated in the paper.

**Comment by KaimingHe** [comment]
Training from scratch can be done by the fine-tuning code, without specifying `--finetune`. You may add model_ema (see DeiT) to get the ema results.

**Comment by tarun005** [comment]
Do you have pre-trained models for training ViT from scratch on ImageNet-1k? (and not finetuned from Imagenet-21k)
