### ISSUE TITLE
Why not release fine-tuned checkpoints?

### ISSUE THREAD

**Issue by franciscoaraposo** [facebookresearch/mae#29]
Title says it all: why not make fine-tuned checkpoints (for places and other benchmarks) available?

**Comment by KaimingHe** [comment]
The ImageNet robustness evaluations are obtained by evaluating the same fine-tuned checkpoints in different variants of the val sets (ImageNet-A etc.). We have not planned to release the checkpoints for iNaturalist/Places. Fine-tuning in these sets are pretty straightforward with an appropriate data loader for these sets.
