### ISSUE TITLE
decoder checkpoint of the pre-trained MAE

### ISSUE THREAD

**Issue by jihoontack** [facebookresearch/mae#3]
Hi,

Thank you for the awesome work and glad to see that the codes are released!

Are there any plans to release the decoder checkpoints of the ViT -Base or -Huge in the near future?

I was trying to run the visualization demo with the ViT-Base model and found that the released checkpoint only consists of the encoder part. (I only found the ViT-Large model’s decoder checkpoint in the visualization demo, i.e., `mae_visualize_vit_large.pth`)

Thank you very much for your time!

Best regards, 
Jihoon

**Comment by KaimingHe** [comment]
In the Colab notebook, download them by:
`!wget -nc https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_base.pth`
`!wget -nc https://dl.fbaipublicfiles.com/mae/visualize/mae_visualize_vit_huge.pth`

Load them by:
`model_mae = prepare_model('mae_visualize_vit_base.pth', 'mae_vit_base_patch16')`
`model_mae = prepare_model('mae_visualize_vit_huge.pth', 'mae_vit_huge_patch14')`

**Comment by jihoontack** [comment]
Thank you very much !

**Comment by jafarinia** [comment]
Why are they different (the encoder only weights and the encoder+decoder weights?)
