### ISSUE TITLE
How MAE is sensitive to batch size?

### ISSUE THREAD

**Issue by HobbitLong** [facebookresearch/mae#32]
Thanks for releasing the code!

I am trying to play with MAE but only with limited # of GPUs. I saw in the doc that we can use `accum_iter` to make the effective batch size the same as the paper (4096). But I wonder what if we use smaller batch sizes (typical case for a university lab)? Do you have some data points on how MAE would perform with batch size smaller than 4096, e.g., ranging from 256 to 1024 etc?

Thank you!

**Comment by KaimingHe** [comment]
A batch size of 1024 should work well: we have verified this for ViT-L. We have not tried 256.

As we can use accumulate gradient in MAE (thanks to the lack of BN or InfoNCE etc.), it is safer to keep the effective batch size as 4096 so you don't need to tweak other hyper-parameters when the batch size changes.

**Comment by HobbitLong** [comment]
Cool, thanks for sharing!
