### ISSUE TITLE
Questions on object detection model

### ISSUE THREAD

**Issue by DianCh** [facebookresearch/mae#36]
Hi, thank you for releasing such a wonderful work. I have a question regarding modifications done on ViT model to adapt it with FPN: as mentioned in the "Benchmarking Detection" paper, in addition to up/down-sampling operations (which are straightforward), the ViT attention is also modified to have local window attention, interleaved with 4 global attention blocks. In this case, how to adapt the ViT pre-trained by MAE (which only has global attention all the way) with the **new attention mechanism**? 

Thanks! I look forward to your reply.

**Comment by KaimingHe** [comment]
The self-attention computation does not require the sequence length to be pre-defined. A self-attention block trained with length X is applicable to another length Y. It is not necessary to make any change here.
