### ISSUE TITLE
Mask ratio in forward method

### ISSUE THREAD

**Issue by Abujaman** [facebookresearch/mae#37]
I was wondering why you put the mask_ratio parameter in the forward method.

Did you experiment with changing the mask ratio during training?
Would that be possible?

Thanks for his great repo!

**Comment by KaimingHe** [comment]
The training process does not require the mask ratio to be fixed.

In the TPU implementation, it is desired to have fixed size tensors, and so we fix the mask ratio for simplicity. But this is not necessary in the GPU implementation. We have not experimented changing it though.
