### ISSUE TITLE
There is a spelling error in the Finetune.md

### ISSUE THREAD

**Issue by CauchyFood** [facebookresearch/mae#40]
The patch_size of the ViT_Huge model is 14, where the parameters of the model are written vit_huge_patch16, and the correct should be vit_huge_patch14. I switched here to vit_huge_patch14, and the result of finetune is *Acc@1 86.926 Acc@5 98.094 loss 0.584

**Comment by endernewton** [comment]
Thanks for pointing this out, we will fix it in the next update.
