### ISSUE TITLE
Can you provide more results about the ViT-B Mask R-CNN+MAE 25ep/50ep

### ISSUE THREAD

**Issue by czczup** [facebookresearch/mae#43]
Thanks for your awesome work!
I am doing some experiments with MAE. Can you provide more results (e.g. mask AP) about these two models (ViT-B Mask R-CNN + MAE 25ep/50ep). I want to cite these data in my paper. 
Thanks! Looking forward to your reply.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/23737120/154794905-417e61ae-0010-4e76-b706-f200ef730604.png">

**Comment by rbgirshick** [comment]
Hi @czczup , the numerical values for the three points you've indicated in your image are: 48.1, 50.1, 50.3.

**Comment by youngwanLEE** [comment]
@rbgirshick Hi,

Could you share the mask AP(AP^{mask}) results, too?

I also want to compare and cite these results in my paper.

Thanks in advance.

**Comment by rbgirshick** [comment]
@youngwanLEE, the corresponding mask AP values are: 43.2, 44.6, 44.9.
