### ISSUE TITLE
[Question] about CNN backbone

### ISSUE THREAD

**Issue by CaptainEven** [facebookresearch/mae#46]
Is it possible to  replace a ViT backbone with a regular CNN backbone like Resnet?

**Comment by gaopengpjlab** [comment]
You can check the following hybrid conv-transformer MAE architecture for your interest.

https://github.com/Alpha-VL/ConvMAE

**Comment by keyu-tian** [comment]
> Is it possible to replace a ViT backbone with a regular CNN backbone like Resnet?

Perhaps this is what you're looking for:  [**MAE on standard ResNets or ConvNeXts**: "Designing BERT for Convolutional Networks: Sparse and Hierarchical Masked Modeling"](https://github.com/keyu-tian/SparK)

**Comment by CaptainEven** [comment]
Thanks for the advice!
