### ISSUE TITLE
Release of the linear probing code

### ISSUE THREAD

**Issue by Jeff-LiangF** [facebookresearch/mae#5]
Hey, 

Thanks for this awesome code! I am wondering whether you plan to release the linear probing code or not. According to the third party [MAE repo](https://github.com/pengzhiliang/MAE-pytorch), the linear probing results seem [hard to be reproduced](https://github.com/pengzhiliang/MAE-pytorch/issues/65). It would be great if you plan to do so. Thanks!

**Comment by endernewton** [comment]
Yes we plan to release them but will do it later as it is less the focus. 

One thing to mention for linear probing is that we use [cls] token outputs as the frozen features. With this (and with other details are handled well), it shouldn't be hard to reproduce the results with the released models.

**Comment by Jeff-LiangF** [comment]
Got it! Thank you.

**Comment by KaimingHe** [comment]
See https://github.com/facebookresearch/mae/blob/main/FINETUNE.md#linear-probing
