### ISSUE TITLE
提供的预训练模型和代码中的模型不一致？

### ISSUE THREAD

**Issue by CGZQQQ** [facebookresearch/mae#50]
Why the structure in the pre-trained checkpoint Vit-Base is different in the models_mae.py. The cls_token layer exist in the  checkpoint Vit-Base you provide, but not in the models_mae.py.

**Comment by KaimingHe** [comment]
cls_token is here:
https://github.com/facebookresearch/mae/blob/main/models_mae.py#L36

**Comment by CGZQQQ** [comment]
Could you provide me your pretrained MAE-model by pytorch?
If I finetuing myself MAE-model with your provide in the mae_facebook github model Vit-Base, whether I should remove the cls_token layer in Vit-Base?




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "facebookresearch/mae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/mae] 提供的预训练模型和代码中的模型不一致？ (Issue #50)





 
Closed #50.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KaimingHe** [comment]
Pre-trained models are here: https://github.com/facebookresearch/mae#fine-tuning-with-pre-trained-checkpoints

**Comment by CGZQQQ** [comment]
I have download the MAE-model as you tell me just now from your github.
The model name is 'mae_pretrain_vit_base(1).pth'&nbsp;
The model Vit-Base has the cls_token layer like this:


but in your models_mae.py the model don't has this layer,like this:

I want to use your encoder of the MAE-model as the backbone of Deeplabv3+ to do the semantic segmentation,whether should I ignore the cls_token layer of your pretrained model or not.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/mae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 下午2:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/mae] 提供的预训练模型和代码中的模型不一致？ (Issue #50)





 
Pre-trained models are here: https://github.com/facebookresearch/mae#fine-tuning-with-pre-trained-checkpoints
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CGZQQQ** [comment]
Thanks for your instruction. I want to konw why you put the cls_token in your pretrain model, it isn't
a layer,just a learnable parameter right?Whether it is useful or necessary when I transfer your model(encoder of the mae-model) to my own semantic segmentation model or not.Look forward to your guidance.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/mae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/mae] 提供的预训练模型和代码中的模型不一致？ (Issue #50)





 
cls_token is here:
 https://github.com/facebookresearch/mae/blob/main/models_mae.py#L36
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
