### ISSUE TITLE
pretrain error

### ISSUE THREAD

**Issue by xiyufeng2** [facebookresearch/mae#55]
hello，author! 
When I run submitit_pretrain.py ,get an erroe :RuntimeError: No shared folder available in line120:'(args.dist_url = get_init_file().as_uri() ).
So I checked and found the args: dist_on_itp=False, dist_url='env://'. And I dont know how to set the Job dir. Can you help?Thanks

**Comment by endernewton** [comment]
Please see https://github.com/facebookresearch/mae/issues/57.
