### ISSUE TITLE
No shared folder available

### ISSUE THREAD

**Issue by xiyufeng2** [facebookresearch/mae#57]
in pretrain and finetune , there is an error :No shared folder available
in function 'get_shared_folder()'

**Comment by endernewton** [comment]
Please change the code in the `submitit` script. Specifically, if no `/checkpoint` is found, it cannot start the experiment.

**Comment by xiyufeng2** [comment]
how to biuld /checkpoint ?
I have no idea what it used for.And there is no detailed instrustion in README.md

**Comment by kwhuang88228** [comment]
Also having the same issue as #55 when running pretrain. I have /checkpoint, /checkpoint/{USER} and /checkpoint/{USER}/experiments. Unclear what to set for --job_dir and getting the following error. Any updates or suggestions? Appreciate any help!

```
Traceback (most recent call last):
  File "submitit_pretrain.py", line 131, in <module>
    main()
  File "submitit_pretrain.py", line 120, in main
    args.dist_url = get_init_file().as_uri()
  File "/anaconda/envs/mae/lib/python3.6/pathlib.py", line 721, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
```
