### ISSUE TITLE
question about transform in validatation

### ISSUE THREAD

**Issue by cobraheleah** [facebookresearch/mae#62]
In finetune，when build validatation transform ,why first Resize to 256 and then CenterCrop to 224 if input size is 224，we usually Resize to 224
![111](https://user-images.githubusercontent.com/63284063/160609252-15340e90-6a6c-43d5-a43d-504da5a339c4.png)
 and then CenterCrop to 224

**Comment by endernewton** [comment]
This is following the standard practice for 224 input. See for example DEiT: https://github.com/facebookresearch/deit/blob/cb29b5efd522a0ac83d64aa8b41fe27cead3a030/datasets.py#L100
