### ISSUE TITLE
Question about the positional embedding?

### ISSUE THREAD

**Issue by exiawsh** [facebookresearch/mae#63]
Hello,
I have some question about the design of positional embedding in your work.
In the vanilla transformer or Detr, the sine and cosine codes are staggered along the dimension.
i.e. 
pe_embedding_table[:, 0::2] = torch.sin(pos_mat/ i_mat)
pe_embedding_table[:, 1::2] = torch.cos(pos_mat/ i_mat)
But in your work, the first 2 / D dimension of the embedding is sine and the last 2 / D dimension is cosine function. Is there any special purpose of this design?
https://github.com/facebookresearch/mae/blob/6a2ba402291005b003a70e99f7c87d1a2c376b0d/util/pos_embed.py#L66

**Comment by endernewton** [comment]
I believe the ordering does not matter in the position embedding. There is no special purpose for this design as both are valid.
