### ISSUE TITLE
The base lr for finetune is different from that in the paper 

### ISSUE THREAD

**Issue by Epiphqny** [facebookresearch/mae#7]
Hello, I noticed that the base lr of the vit-base in https://github.com/facebookresearch/mae/blob/main/FINETUNE.md is 5e-4 with layer-wise decay of 0.65, but in the paper the base lr is 1e-3 with  layer-wise decay of 0.75, why are they different?

**Comment by KaimingHe** [comment]
See here: https://github.com/facebookresearch/mae/blob/main/FINETUNE.md#notes
