### ISSUE TITLE
Which version of ImageNet do you use?

### ISSUE THREAD

**Issue by 1049451037** [facebookresearch/mae#72]
Is [this](https://www.kaggle.com/c/imagenet-object-localization-challenge/overview/description) is the one?

I met some error after downloading it and run `python main_finetune.py`:

```bash
RuntimeError: Found 0 files in subfolders of: /imagenet1k/ILSVRC/Data/CLS-LOC/val
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp
```

**Comment by nhonth** [comment]
I think you need to convert the validation set into the ImageFolder format (one folder per category). I downloaded imagenet from kaggle and then manually converted the validation set. The training set was already in the right format.

**Comment by 1049451037** [comment]
Well, I get it. Thank you!
