### ISSUE TITLE
Typo in FINETUNE.md

### ISSUE THREAD

**Issue by vtddggg** [facebookresearch/mae#74]
Hi, @KaimingHe @endernewton 

It looks there is a typo in FINETUNE.md: https://github.com/facebookresearch/mae/blob/6a2ba402291005b003a70e99f7c87d1a2c376b0d/FINETUNE.md?plain=1#L52
`vit_huge_patch16 ` ——>`vit_huge_patch14 `

I didn't check them carefully, and not sure if such a typo exist other similar place.  Thanks for your excellent MAE！

**Comment by endernewton** [comment]
Yes it is fixed now. See also: https://github.com/facebookresearch/mae/issues/40
