### ISSUE TITLE
Locally multi-gpu training 

### ISSUE THREAD

**Issue by ofir1080** [facebookresearch/mae#81]
Hi!
Thanks for this great work!
I would like to pretrain locally, not using Slurm. I could not find any implementations. Is there one?
Thanks

**Comment by endernewton** [comment]
There is. For example `OMP_NUM_THREADS=1 python -m torch.distributed.launch --nproc_per_node=8 main_pretrain.py ...`.

**Comment by kalyani7195** [comment]
I want to use two nodes, but want to launch training
 using main_pretrain.py. what is the command I should be using? thanks!
